<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Hyva\Theme\ViewModel\BlockJsDependencies;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductListItem;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Block\Product\AbstractProduct;
use Magento\Catalog\Helper\Output as CatalogOutputHelper;
use Magento\Catalog\ViewModel\Product\OptionsData as ProductOptionsData;
use Magento\Framework\Escaper;

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundHelper
// phpcs:disable Generic.Files.LineLength.TooLong

/** @var AbstractProduct $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);

/** @var ProductListItem $productListItemViewModel */
$productListItemViewModel = $viewModels->require(ProductListItem::class);

/** @var CatalogOutputHelper $catalogOutputHelper */
$catalogOutputHelper = $this->helper(CatalogOutputHelper::class);

/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);
/** @var Wishlist $wishlistViewModel */
$wishlistViewModel = $viewModels->require(Wishlist::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$productOptionsViewmodel = $viewModels->require(ProductOptionsData::class);

/** @var Magento\Catalog\Model\Product $product */
if (! ($product = $block->getData('product'))) {
    return;
}
$imageDisplayArea = $block->getData('image_display_area');
$templateType = $block->getData('template_type');
$viewMode = $block->getData('view_mode');
$showDescription = $block->getData('show_description');
$showAddToWishlist = $wishlistViewModel->isEnabled();
$showAddToCompare = $compareViewModel->showInProductList();
$viewIsGrid = $viewMode === 'grid';
$productType = $product->getTypeId();
$isProductGroupedOrBundle = $productType === 'bundle' || $productType === "grouped";
$productId = $product->getId();
$options   = $productOptionsViewmodel->getOptionsData($product);

$hideDetails       = $block->getData('hide_details') ?: false;
$hideRatingSummary = $block->getData('hide_rating_summary') ?: false;

$imageCustomAttributes = $product->getData('image_custom_attributes')
    ?? $block->getData('image_custom_attributes')
    ?? [];
$productName = $catalogOutputHelper->productAttribute($product, $product->getName(), 'name');

// Ensure the required JS is rendered on the page
$viewModels->require(BlockJsDependencies::class)->setBlockTemplateDependency($block, 'Magento_Catalog::product/list/js/price-box.phtml');

?>

<?php if ($product->isSaleable()): ?>
<form method="post"
    action="<?= $escaper->escapeUrl($productViewModel->getAddToCartUrl($product, ['useUencPlaceholder' => true])) ?>"
    class="item product product-item product_addtocart_form flex flex-col w-full relative <?= $viewIsGrid ? '' : 'md:flex-row' ?>"
    <?php if ($product->getOptions()): ?>
    enctype="multipart/form-data"
    <?php endif; ?>
>
    <?= /** @noEscape */ $block->getBlockHtml('formkey') ?>
    <input type="hidden" name="product" value="<?= (int)$productId ?>"/>
    <?php foreach ($options as $optionItem): ?>
    <input type="hidden"
           name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
           value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
    <?php endforeach; ?>
    <?php else: ?>
<div class="item product product-item flex flex-col w-full <?= $viewIsGrid ? '' : 'md:flex-row' ?>">
<?php endif; ?>
    <?php /* Product Image */ ?>
    <a href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
        title="<?= $escaper->escapeHtmlAttr($product->getName()) ?>"
        class="product photo product-item-photo block mx-auto mb-3 <?= $viewIsGrid ? '' : 'md:w-2/6 md:mb-0 md:mr-5 md:shrink-0' ?>"
        tabindex="-1"
    >
        <?= $block->getImage($product, $imageDisplayArea)
            ->setTemplate('Magento_Catalog::product/list/image.phtml')
            ->setData('custom_attributes', $imageCustomAttributes)
            ->setProductId($productId)
            ->toHtml(); ?>
    </a>
    <div class="product-info flex flex-col grow">
        <div class="mt-0.5 mb-2.5 items-center justify-center text-primary font-semibold text-xl <?= $viewIsGrid ? '' : 'md:text-left' ?>">
            <a
                class="product-item-link"
                href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
                :id="`slide-desc-<?= $escaper->escapeHtmlAttr($product->getId()) ?>-${$id('slider-id')}`"
            >
                <?= /* @noEscape */ $productName ?>
            </a>
        </div>
        <?php if ($product->isAvailable() && !$hideDetails): ?>
            <?= $block->getProductDetailsHtml($product) ?>
        <?php endif; ?>
        <?php if ($showDescription): ?>
        <div class="mt-2 mb-1 items-center justify-center text-primary text-center <?= $viewIsGrid ? '' : 'md:text-left' ?>">
            <?= /* @noEscape */ $productViewModel->getShortDescriptionForProduct($product) ?>
        </div>
        <?php endif; ?>

        <?php if ($isProductGroupedOrBundle): ?>
            <span class="sr-only">
                <?= $escaper->escapeHtml(__('The price depends on the options chosen on the product page')) ?>
            </span>
        <?php endif; ?>

        <div class="pt-1 pb-4"
             x-data="initPriceBox()"
             x-defer="intersect"
             @update-prices-<?= (int)$productId ?>.window="updatePrice($event.detail);"
        >
            <?= /* @noEscape */ $productListItemViewModel->getProductPriceHtml($product) ?>
        </div>
        <?php if (!$hideRatingSummary): ?>
            <div class="py-1 <?= $viewIsGrid ? '' : 'md:mx-0 md:w-auto' ?>">
                <?= $block->getReviewsSummaryHtml($product, 'short') ?>
            </div>
        <?php endif; ?>
        <div class="mt-auto pt-4 flex flex-wrap items-center gap-y-4 gap-x-2
            <?= $viewIsGrid ? '' : '' ?>">
            <?php if ($product->isSaleable()): ?>
                <?php if ($isProductGroupedOrBundle): ?>
                <a
                    href="<?= $escaper->escapeUrl($product->getProductUrl()) ?>"
                    class="w-auto btn btn-primary justify-center uppercase <?= $viewIsGrid ? 'mr-auto' : 'mr-auto md:mr-0' ?>"
                    title="<?= $escaper->escapeHtmlAttr(__('Configure %1 on the product page')) ?>"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Configure %1 on the product page', $productName)) ?>"
                >
                    <?= $escaper->escapeHtml(__('View Details')) ?>
                </a>
                <?php else: ?>
                <button
                    class="w-auto btn btn-primary justify-center uppercase <?= $viewIsGrid ? 'mr-auto' : 'mr-auto md:mr-0' ?>"
                    title="<?= $escaper->escapeHtmlAttr(__('Add to Cart') . ' ' . $productName) ?>"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Cart') . ' ' . $productName) ?>"
                    data-addto="cart"
                >
                    <?= $escaper->escapeHtml(__('Add to Cart')) ?>
                </button>
                <?php endif; ?>

            <?php else: ?>
            <div class="w-auto justify-center <?= $viewIsGrid ? 'mr-auto' : 'mr-auto md:mr-0' ?>">
                <?= $block->getChildBlock('stockstatus')->setData('product', $product)->toHtml() ?>
            </div>
            <?php endif; ?>
            <div class="absolute top-0 right-0 flex flex-col gap-2.5">
                <?php if ($showAddToWishlist): ?>
                <button x-data="initWishlist()"
                        x-defer="intersect"
                        @click.prevent="addToWishlist(<?= (int)$productId ?>)"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Wish List') . ' ' . $productName) ?>"
                        type="button"
                        class="rounded-full w-10 h-10 bg-floralwhite p-0 border-0 inline-flex shrink-0 items-center justify-center text-copper hover:text-white hover:bg-copper add-to-wishlist"
                        data-addto="wishlist"
                >
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.501 5.501 0 0 0-7.78 7.78L12 21.23l8.84-8.84a5.5 5.5 0 0 0 0-7.78" stroke="#A36638" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
                    </svg>
                </button>
                <?php endif; ?>
                <?php if ($showAddToCompare): ?>
                <button x-data="initCompareOnProductList()"
                        x-defer="intersect"
                        @click.prevent="addToCompare(<?= (int)$productId ?>)"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare') . ' ' . $productName) ?>"
                        type="button"
                        class="rounded-full w-10 h-10 bg-floralwhite p-0 border-0 inline-flex shrink-0 items-center justify-center text-copper hover:text-white hover:bg-copper add-to-compare"
                        data-addto="compare"
                >
                    <svg width="26" height="26" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <g clip-path="url(#a)">
                            <path d="M10.833 3.25H5.417c-1.197 0-2.167.97-2.167 2.167v15.167c0 1.197.97 2.166 2.167 2.166h5.416v2.167H13V1.084h-2.167zm0 16.25H5.417l5.416-6.5zm9.75-16.25h-5.416v2.167h5.416V19.5L15.167 13v9.75h5.416c1.197 0 2.167-.97 2.167-2.166V5.417c0-1.197-.97-2.167-2.167-2.167" fill="#A36638"/>
                        </g>
                        <defs>
                            <clipPath id="a">
                                <path fill="#fff" d="M0 0h26v26H0z"/>
                            </clipPath>
                        </defs>
                    </svg>
                </button>
                <?php endif; ?>
                <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                    <?= $addToBlock->setProduct($product)->getChildHtml() ?>
                <?php endif; ?>
            </div>
        </div>
    </div>
<?php if ($product->isSaleable()): ?>
</form>
<?php else: ?>
</div>
<?php endif; ?>
