<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;
use Magento\LayeredNavigation\Block\Navigation\State;

/** @var State $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$filters = $block->getActiveFilters();
$isFilterDefaultOpen = $block->getOpen() !== null ? (bool) $block->getOpen() : true;
$isFilterStyleChips = (string) $block->getFilterStyle() === "chips";
$filterChipStyle = 'py-2 px-2.5 rounded-md hover:bg-red-300 hover:text-red-800 focus:outline-red-300 active:bg-red-400 active:text-red-900';

if (empty($filters)) {
    return '';
}
?>

<div class="filter-current group"<?= $isFilterDefaultOpen ? ' open' : '' ?>>
    <ul
            id="active-filtering-content"
            class="block-content filter-content py-2 <?= $isFilterStyleChips ? 'flex flex-wrap gap-2' : 'space-y-3' ?>"
            aria-labelledby="active-filtering-heading"
    >
        <?php foreach ($filters as $filter): ?>
            <?php
            $filterName = $filter->getName();
            $filterLabel = $block->stripTags($filter->getLabel());
            $filterIsBool = $filter->getValue() === "0" || $filter->getValue() === "1";
            ?>
            <li class="inline-block mr-4">
                <a
                        href="<?= $escaper->escapeUrl($filter->getRemoveUrl()) ?>"
                        class="item group/active-filter flex justify-between items-center gap-1 text-sm transition-colors
                        <?= $isFilterStyleChips ? 'text-current ' . $filterChipStyle : '' ?>"
                        title="<?= $escaper->escapeHtmlAttr(__('Remove filter for %1: %2', $filterName, $filterLabel)) ?>"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Remove filter for %1: %2', $filterName, $filterLabel)) ?>"
                >
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="-3 -3 26 26" fill="currentColor" class="action remove bg-copper rounded-full text-white h-4 w-4" width="10" height="10" aria-hidden="true">
                        <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                    </svg>
                    <span>
                        <span class="filter-label <?= $isFilterStyleChips
                            ? ($filterIsBool ? 'opacity-60' : 'sr-only')
                            : 'font-normal' ?>"><?= $escaper->escapeHtml(__($filterName)) ?>:</span>
                        <span class="filter-value <?= $isFilterStyleChips
                            ? 'font-normal'
                            : 'font-semibold' ?>"><?= $escaper->escapeHtml($filterLabel) ?></span>
                    </span>
                </a>
            </li>
        <?php endforeach; ?>
        <?php if ($block->getLayer()->getState()->getFilters()): ?>
            <li class="inline-block ml-2 relative top-0.5">
                <a
                        href="<?= $escaper->escapeUrl($block->getClearUrl()) ?>"
                        class="block-actions filter-actions text-sm !mt-0 float-left transition-colors
                        <?= $isFilterStyleChips
                            ? 'flex ' . $filterChipStyle
                            : 'block mt-4' ?>"
                        title="<?= $escaper->escapeHtmlAttr(__('Remove all filters')) ?>"
                        aria-label="<?= $escaper->escapeHtmlAttr(__('Remove all filters')) ?>"
                ><?= $escaper->escapeHtml(__('Clear All')) ?></a>
            </li>
        <?php endif; ?>
    </ul>
</div>
