<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;
use Magento\LayeredNavigation\Block\Navigation;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Navigation $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var HeroiconsSolid $heroiconsSolid */
$heroiconsSolid = $viewModels->require(HeroiconsSolid::class);

$activeFilterStyle = $block->getActiveStyle();
$activeIsOpen = $block->getActiveOpen();
$showFilterInput = $block->getShowInput() !== null ? (bool) $block->getShowInput() : true;
$showFilterPriceSlider = $block->getShowPriceSlider() !== null ? (bool) $block->getShowPriceSlider() : true;
$showFilterPriceOptions = $block->getShowPriceOptions() !== null ? (bool) $block->getShowPriceOptions() : false;
$openFiltersByIds = (array) $block->getOpenByIds() ?: [];
$maxPriceFallbackValue = (int) $block->getMaxPriceFallbackValue() ?: 1000
?>

<?php if ($block->canShowBlock()): ?>
    <div
        class="md:my-8 mt-8 md:p-0 px-4 py-2.5 md:border-0 border border-copper rounded-lg"
        role="region"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Product filters')) ?>"
        x-data="initLayeredNavigation()"
        x-defer="intersect"
        x-bind="eventListeners"
    >
        <h2 id="filters-heading" class="md:!hidden block-title">
            <button
                type="button"
                @click="blockOpen = !blockOpen"
                class="btn btn-secondary hover:text-copper border-none gap-2 justify-between w-full text-start text-base font-semibold
                    md:!shadow-none md:!bg-transparent md:!text-current md:text-2xl p-0"
                aria-controls="filters-content"
                :aria-expanded="blockOpen"
                :aria-disabled="!isMobile"
                :disabled="!isMobile ? '' : null"
            >
                <span><?= $escaper->escapeHtml(__('Shop By')) ?></span>
                <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" x-ref="LayeredNavigationMobileToggleIcon" :class="{ 'rotate-180': blockOpen }" fill="currentColor" class="text-copper rotate-0" width="24" height="24" aria-hidden="true">
                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd"></path>
                </svg>
            </button>
        </h2>
        <a href="#product-list" class="block sr-only focus:not-sr-only">
            <span class="block my-2 py-2.5 px-4 bg-blue-600 text-white text-center rounded-sm"><?= $escaper->escapeHtml(__('Skip to product list')) ?></span>
        </a>
        <div
            id="filters-content"
            class="block-content filter-content hidden md:block mt-4 bg-white"
            :class="{ 'hidden': !blockOpen }"
        >
            <?php foreach ($block->getFilters() as $filter): ?>
                <?php $isFilterDefaultOpen = in_array($filter->getRequestVar(), $openFiltersByIds); ?>
                <?php if ($filter->getItemsCount() || ($filter->getRequestVar() === 'price' && $showFilterPriceSlider)): ?>
                    <details
                        id="<?= $escaper->escapeHtmlAttr($filter->getRequestVar()) ?>"
                        class="filter-option group mb-4 last:mb-0"
                        <?= $isFilterDefaultOpen ? 'open': ''; ?>
                    >
                        <summary
                            class="block-title [&::-webkit-details-marker]:hidden p-2.5 bg-pearl flex items-center justify-between font-medium md:text-lg cursor-pointer outline-offset-2"
                            aria-label="<?= $escaper->escapeHtml(__('%1 filter', $filter->getName())) ?>"
                        >
                            <h3 class="text-xl font-semibold"><?= $escaper->escapeHtml(__($filter->getName())) ?></h3>
                            <span class="text-blue-700 transition-transform transform duration-300 ease-in-out group-open:rotate-180">
                                <?= $heroiconsSolid->chevronDownHtml('text-gray-erieb', 24, 24, ["aria-hidden" => "true"]); ?>
                            </span>
                        </summary>
                        <div class="filter-options-content p-2">
                            <?php if ($filter->getRequestVar() === 'price' && $showFilterPriceSlider && $block->getChildBlock('renderer-price')): ?>
                                <?= /* @noEscape */ $block->getChildBlock('renderer-price')
                                    ->setFilterTitle($filter->getName())
                                    ->setFilterId($filter->getRequestVar())
                                    ->setMaxPriceFallbackValue($maxPriceFallbackValue)
                                    ->render($filter); ?>
                            <?php else: ?>
                                <?= /* @noEscape */ $block->getChildBlock('renderer')
                                    ->setFilterTitle($filter->getName())
                                    ->setFilterId($filter->getRequestVar())
                                    ->setShowInput($showFilterInput)
                                    ->render($filter); ?>
                            <?php endif; ?>
                        </div>
                    </details>
                <?php endif; ?>
            <?php endforeach; ?>
        </div>
    </div>
    <script>
        function initLayeredNavigation() {
            return {
                isMobile: false,
                blockOpen: false,
                init() {
                    this.checkIsMobileResolution();
                },
                checkIsMobileResolution() {
                    const mobileElement = this.$refs.LayeredNavigationMobileToggleIcon;
                    this.isMobile = mobileElement
                        ? getComputedStyle(mobileElement).display !== "none"
                        : window.matchMedia('(max-width: 767px)').matches; // Fallback to `md` breakpoint
                },
                eventListeners: {
                    ['@resize.window.debounce']() {
                        this.checkIsMobileResolution();
                    },
                    ['@visibilitychange.window.debounce']() {
                        this.checkIsMobileResolution();
                    },
                },
            }
        }
    </script>
<?php endif; ?>
