<?php

declare(strict_types=1);

// phpcs:disable Magento2.Files.LineLength.MaxExceeded

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Checkout\Block\Cart\Item\Renderer;
use Magento\Framework\Escaper;
use Hyva\Theme\ViewModel\HeroiconsOutline;

/** @var Renderer $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

$item = $block->getItem();
$product = $item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();

/** @var HeroiconsOutline $heroIcons */
$heroIcons = $viewModels->require(HeroiconsOutline::class);

?>
<tbody class="cart item bg-white border-t border-pearl">
<tr class="item-info align-top text-left lg:text-right flex flex-wrap lg:table-row"
    x-init="registerItem('<?= $item->getId(); ?>', '<?= $item->getQty(); ?>')">
    <td data-th="<?= $escaper->escapeHtml(__('Item')) ?>"
        class="col item pt-6 sm:px-4 flex flex-wrap gap-8 text-left w-full sm:flex-nowrap lg:w-auto">
        <?php if ($block->hasProductUrl()): ?>
        <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"
           title="<?= $escaper->escapeHtmlAttr($block->getProductName()) ?>"
           tabindex="-1"
           class="product-item-photo shrink-0">
            <?php else: ?>
            <span class="product-item-photo shrink-0">
            <?php endif;?>
            <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')
                ->setTemplate('Magento_Catalog::product/image.phtml')
                ->toHtml() ?>
            <?php if ($block->hasProductUrl()): ?>
        </a>
    <?php else: ?>
        </span>
    <?php endif; ?>
        <div class="product-item-details grow">
            <strong class="product-item-name break-all">
                <?php if ($block->hasProductUrl()): ?>
                    <a href="<?= $escaper->escapeUrl($block->getProductUrl()) ?>"><?= $escaper->escapeHtml($block->getProductName()) ?></a>
                <?php else: ?>
                    <?= $escaper->escapeHtml($block->getProductName()) ?>
                <?php endif; ?>
            </strong>
            <?php if ($options = $block->getOptionList()): ?>
                <dl class="item-options w-full break-all mt-4 pb-2 text-sm clearfix">
                    <?php foreach ($options as $option): ?>
                        <?php $formatedOptionValue = $block->getFormatedOptionValue($option) ?>
                        <dt class="font-bold float-left clear-left mr-2 mb-2"><?= $escaper->escapeHtml($option['label']) ?>:</dt>
                        <dd class="float-left">
                            <?php if (isset($formatedOptionValue['full_view'])): ?>
                                <?= $escaper->escapeHtml($formatedOptionValue['full_view']) ?>
                            <?php else: ?>
                                <?= $escaper->escapeHtml($formatedOptionValue['value'], ['span', 'a']) ?>
                            <?php endif; ?>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif;?>
            <?php if ($messages = $block->getMessages()): ?>
                <?php foreach ($messages as $message): ?>
                    <div class= "cart item message <?= $escaper->escapeHtmlAttr($message['type']) ?>">
                        <div><?= $escaper->escapeHtml($message['text']) ?></div>
                    </div>
                <?php endforeach; ?>
            <?php endif; ?>
            <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
            <?php if ($addInfoBlock): ?>
                <?= $addInfoBlock->setItem($item)->toHtml() ?>
            <?php endif;?>
        </div>
    </td>

    <td class="col price sm:pt-6 pt-2 sm:px-4 flex items-center sm:block w-full sm:w-1/3 lg:w-auto lg:table-cell">
            <span class="lg:hidden font-bold sm:mt-2 sm:pr-0 pr-2.5">
                <?= $escaper->escapeHtml(__('Price')) ?>
            </span>
        <?= $block->getUnitPriceHtml($item) ?>
    </td>

    <td class="col qty sm:pt-6 lg:pt-2 flex items-center sm:block w-full sm:w-1/3 lg:w-auto lg:table-cell">
            <span class="lg:hidden font-bold sm:pr-0 pr-2.5">
                <?= $escaper->escapeHtml(__('Qty')) ?>
            </span>
        <div class="qty sm:mt-5 mt-2 max-w-40 sm:mx-auto ml-2">
            <label for="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-qty"
                   class="flex items-center gap-1 border border-pearl"
            >
                <button type="button"
                        class="btn p-3 rounded bg-transparent shadow-none text-gray-erieb"
                        aria-label="decrement"
                        @click="prepareQtyAndDispatch('<?= $item->getId(); ?>', 'decrement')">
                    <?= $heroIcons->minusHtml('', 20, 20, ['aria-hidden' => 'true']); ?>
                </button>
                <span class="label sr-only"><?= $escaper->escapeHtml(__('Qty')) ?></span>
                <input id="cart-<?= $escaper->escapeHtmlAttr($item->getId()) ?>-qty"
                       name="cart[<?= $escaper->escapeHtmlAttr($item->getId()) ?>][qty]"
                       value="<?= $escaper->escapeHtmlAttr($block->getQty()) ?>"
                       type="number"
                       size="4"
                       step="any"
                       title="<?= $escaper->escapeHtmlAttr(__('Qty')) ?>"
                       class="border-none qty shadow-none font-medium form-input w-16 text-center md:pl-3 py-3 px-0 rounded-none"
                       required
                       min="0"
                       data-role="cart-item-qty"
                       @change.debounce.200ms="dispatchAjaxSubmitEvent($event.target)"
                />
                <button type="button"
                        class="btn p-3 rounded bg-transparent shadow-none text-gray-erieb"
                        aria-label="increment"
                        @click="prepareQtyAndDispatch('<?= $item->getId(); ?>', 'increment')">
                    <?= $heroIcons->plusHtml('', 20, 20, ['aria-hidden' => 'true']); ?>
                </button>
            </label>
        </div>
    </td>

    <td class="col subtotal sm:pt-6 sm:px-4 flex items-center sm:block w-full sm:w-1/3 lg:w-auto lg:table-cell">
            <span class="lg:hidden font-bold sm:pr-0 pr-2.5">
                <?= $escaper->escapeHtml(__('Subtotal')) ?>
            </span>
        <?= $block->getRowTotalHtml($item) ?>
    </td>
</tr>
<tr class="item-actions">
    <td colspan="4">
        <div class="flex justify-end gap-4 p-4 pt-2">
            <?= /* @noEscape */ $block->getActions($item) ?>
        </div>
    </td>
</tr>
</tbody>
