<?php

declare(strict_types=1);

use Hyva\Theme\Block\SortableItem;
use Magento\Framework\Escaper;

/** @var SortableItem $block */
/** @var Escaper $escaper */

$label = $block->getLabel();
$path = $block->getPath();
?>

<?php if ($label && $path): ?>
    <a id="<?= $escaper->escapeHtmlAttr($block->getNameInLayout()) ?>"
       class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-pearl"
       href="<?= $escaper->escapeUrl($block->getUrl($path)) ?>"
       title="<?= $escaper->escapeHtmlAttr($label) ?>"
    >
        <?= $escaper->escapeHtml($label) ?>
    </a>
<?php endif; ?>
