<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\CurrentProduct;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\ProductCompare;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductCompare $compareViewModel */
$compareViewModel = $viewModels->require(ProductCompare::class);

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var CurrentProduct $currentProduct */
$currentProduct = $viewModels->require(CurrentProduct::class);

/** @var Product $product */
$product = $currentProduct->get();

if (!$product->getId() || !$compareViewModel->showOnProductPage()) {
    return;
}
?>
<script>
    function initCompareOnProductView() {
        return {
            addToCompare: function (productId) {
                const formKey = hyva.getFormKey();
                const postUrl = BASE_URL + 'catalog/product_compare/add/';

                fetch(postUrl, {
                    "headers": {
                        "content-type": "application/x-www-form-urlencoded; charset=UTF-8",
                    },
                    "body": "form_key=" + formKey + "&product=" + productId + "&uenc=" + hyva.getUenc(),
                    "method": "POST",
                    "mode": "cors",
                    "credentials": "include"
                }).then(function (response) {
                    if (response.redirected) {
                        window.location.href = response.url;
                    }
                }).catch(function (error) {
                    typeof window.dispatchMessages !== "undefined" && window.dispatchMessages(
                        [{
                            type: "error",
                            text: error
                        }], 5000
                    );
                });
            }
        };
    }
</script>

<button x-data="initCompareOnProductView()"
        @click.prevent="addToCompare(<?= (int)$product->getId() ?>)"
        title="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Add to Compare')) ?>"
        id="add-to-compare"
        class="rounded-full w-14 h-14 bg-floralwhite p-0 border-0 inline-flex shrink-0 items-center justify-center
        text-copper hover:text-white hover:bg-copper add-to-compare ml-3"
        data-addto="compare"
>
    <svg width="30" height="30" viewBox="0 0 26 26" fill="none" xmlns="http://www.w3.org/2000/svg">
        <g clip-path="url(#a)">
            <path d="M10.833 3.25H5.417c-1.197 0-2.167.97-2.167 2.167v15.167c0 1.197.97 2.166 2.167 2.166h5.416v2.167H13V1.084h-2.167zm0 16.25H5.417l5.416-6.5zm9.75-16.25h-5.416v2.167h5.416V19.5L15.167 13v9.75h5.416c1.197 0 2.167-.97 2.167-2.166V5.417c0-1.197-.97-2.167-2.167-2.167" fill="#B6713E"/>
        </g>
        <defs>
            <clipPath id="a">
                <path fill="#fff" d="M0 0h26v26H0z"/>
            </clipPath>
        </defs>
    </svg>
</button>
