<?php

declare(strict_types=1);

use Magento\Checkout\Block\Cart;
use Magento\Framework\Escaper;

/** @var Cart $block */
/** @var Escaper $escaper */
?>

<div class="w-full">
    <div class="w-full lg:w-1/4 float-left lg:float-right lg:order-2 top-0 lg:sticky bg-floralwhite px-5">
        <div class="flex pb-3 my-2 border-b border-pearl flex-col">
            <h2 class="w-full text-2xl text-center text-primary title-font font-base md:text-left">
                <?= $escaper->escapeHtml(__('Summary')) ?>
            </h2>
        </div>
        <?= $block->getChildHtml('cart.summary') ?>
    </div>
    <div class="w-full lg:w-3/4 float-left lg:order-1 lg:pr-8">
        <?= $block->getChildHtml('form_before') ?>
        <?= $block->getChildHtml('cart-items') ?>
        <?= $block->getChildHtml('checkout_cart_widget') ?>
    </div>
    <div class="w-full lg:w-3/4 lg:pr-8">
        <?= $block->getChildHtml('cart.discount') ?>
    </div>
</div>
