<?php

declare(strict_types=1);

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\Model\ViewModelRegistry;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

$label = $block->getData('label') ?? __('My Wish List');
$urlPath = $block->getData('path') ?? 'wishlist';
?>

<a
    id="<?= $escaper->escapeHtmlAttr($block->getNameInLayout()) ?>"
    class="block md:pl-6 sm:pl-4 pl-1 relative"
    href="<?= $escaper->escapeUrl($block->getUrl($urlPath)) ?>"
    title="<?= $escaper->escapeHtmlAttr($label) ?>"
    x-data="{ itemCount: 0 }"
    @private-content-loaded.window="itemCount = parseInt($event.detail.data.wishlist.counter)"
>
    <div class="sr-only"><?= $escaper->escapeHtml($label) ?></div>
    <div>
        <svg class="sm:w-6 w-5 sm:h-6 h-5" width="24" height="24" viewBox="0 0 24 22" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M20.84 3.61a5.5 5.5 0 0 0-7.78 0L12 4.67l-1.06-1.06a5.501 5.501 0 0 0-7.78 7.78L12 20.23l8.84-8.84a5.5 5.5 0 0 0 0-7.78" stroke="#222" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
    </div>
    <template x-if="itemCount">
        <span class="absolute -top-2.5 -right-2.5 min-w-4.5 h-4.5 p-1 rounded-full bg-copper text-white text-xs font-semibold leading-none text-center uppercase tabular-nums"
              x-text="`${itemCount}`"></span>
    </template>
</a>
