<?php

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Catalog\Block\Product\ProductList\Toolbar;
use Magento\Framework\Escaper;

/** @var Toolbar $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

// phpcs:disable Generic.Files.LineLength
?>

<?php if ($block->isEnabledViewSwitcher()): ?>
    <?php $modes = $block->getModes(); ?>
    <?php if ($modes && count($modes) > 1): ?>
        <nav
            class="modes flex justify-center"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Products view mode')) ?>"
        >
            <style>
                .modes-mode.mode-grid {
                    background-image: url(data:image/svg+xml,%3Csvg%20width%3D%2224%22%20height%3D%2224%22%20viewBox%3D%220%200%2033%2032%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Cpath%20d%3D%22M12.753%201H1.121v11.667h11.632zm18.279%200H19.4v11.667h11.632zm0%2018.333H19.4V31h11.632zm-18.279%200H1.121V31h11.632z%22%20stroke%3D%22%23A36638%22%20stroke-width%3D%222%22%20stroke-linecap%3D%22round%22%20stroke-linejoin%3D%22round%22%2F%3E%3C%2Fsvg%3E);
                }

                .modes-mode.mode-list {
                    background-image: url(data:image/svg+xml,%3Csvg%20width%3D%2224%22%20height%3D%2224%22%20viewBox%3D%220%200%2031%2030%22%20fill%3D%22none%22%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%3E%3Crect%20x%3D%22.09%22%20width%3D%2229.961%22%20height%3D%223.333%22%20rx%3D%221.667%22%20fill%3D%22%23A36638%22%2F%3E%3Crect%20x%3D%22.09%22%20y%3D%2212.857%22%20width%3D%2229.961%22%20height%3D%223.333%22%20rx%3D%221.667%22%20fill%3D%22%23A36638%22%2F%3E%3Crect%20x%3D%22.09%22%20y%3D%2225.714%22%20width%3D%2229.961%22%20height%3D%223.333%22%20rx%3D%221.667%22%20fill%3D%22%23A36638%22%2F%3E%3C%2Fsvg%3E);
                }
            </style>
            <?php foreach ($block->getModes() as $code => $label): ?>
                <button
                    type="button"
                    class="modes-mode w-6 h-6 ml-3 mode-<?= $escaper->escapeHtmlAttr(strtolower($code)) ?> <?= ($block->isModeActive($code)) ? 'active' : 'opacity-50 hover:opacity-100' ?>"
                    title="<?= $escaper->escapeHtmlAttr($label) ?>"
                    <?php if ($block->isModeActive($code)): ?>
                        disabled
                    <?php else: ?>
                        @click.prevent="changeUrl(
                            'product_list_mode',
                            '<?= $escaper->escapeHtmlAttr(strtolower($code)) ?>',
                            options.modeDefault
                        )"
                    <?php endif; ?>
                    data-role="mode-switcher"
                    data-value="<?= $escaper->escapeHtmlAttr(strtolower($code)) ?>"
                    aria-label="<?= $escaper->escapeHtmlAttr(__('Products view mode - %1', $label)) ?>"
                ></button>
            <?php endforeach; ?>
        </nav>
    <?php else: ?>
        <div class="modes w-20 order-1 col-span-1 sm:col-span-2 md:col-span-1 lg:col-span-2"></div>
    <?php endif; ?>
<?php endif; ?>
