<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsOutline;
use Hyva\Theme\ViewModel\Navigation;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var HeroiconsOutline $heroicons */
$heroicons = $viewModels->require(HeroiconsOutline::class);

/** @var Navigation $viewModelNavigation */
$viewModelNavigation = $viewModels->require(Navigation::class, $block);

$uniqueId = '_' . uniqid();

// Order is important here: 1. build the menu data, 2. then set the cache tags from the view model identities
$menuItems = $viewModelNavigation->getNavigation(4);
$block->setData('cache_tags', $viewModelNavigation->getIdentities());

?>
<nav
    x-data="initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?>()"
    @load.window="setActiveMenu($root)"
    @keydown.window.escape="closeMenu()"
    class="z-20 order-2 sm:order-1 lg:order-2 navigation lg:hidden w-12 h-12"
    aria-label="<?= $escaper->escapeHtmlAttr(__('Site navigation')) ?>"
    role="navigation"
    @click.away="open = false"
>
    <!-- mobile -->
    <button
        x-ref="mobileMenuTrigger"
        @click="openMenu()"
        :class="{'overflow-x-hidden overflow-y-auto fixed top-0 left-0 w-full' : open}"
        type="button"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Open menu')) ?>"
        aria-haspopup="menu"
        :aria-expanded="open"
        :hidden="open"
    >
        <?= $heroicons->menuHtml('py-3 pr-3', 48, 48, [":class" => "{ 'hidden' : open, 'block': !open }", "aria-hidden" => "true"]) ?>
    </button>
    <div
        x-ref="mobileMenuNavLinks"
        class="
            fixed top-0 left-0 w-9/12 h-full hidden flex-col bg-white shadow-4xl overflow-y-auto overflow-x-hidden"
        :class="{ 'flex': open, 'hidden': !open }"
        :aria-hidden="open ? 'false' : 'true'"
        role="dialog"
        aria-modal="true"
    >

        <div class="flex justify-between items-center border-b border-copper">
            <div class="w-32 pl-8 py-4">
                <?= $block->getChildHtml('mobile-menu-logo'); ?>
            </div>
            <button
                @click="closeMenu()"
                class="flex justify-end w-16 self-end mb-1"
                aria-label="<?= $escaper->escapeHtmlAttr(__('Close menu')) ?>"
                type="button"
            >
                <?= $heroicons->xHtml('hidden p-4', 64, 64, [":class" => "{ 'hidden' : !open, 'block': open }", "aria-hidden" => "true"]) ?>
            </button>
        </div>
        <ul
            class="border-t border-pearl flex flex-col gap-y-1"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Site navigation links')) ?>"
        >
            <?php foreach ($menuItems as $index => $menuItem): ?>
                <li
                    data-child-id="<?= $escaper->escapeHtmLAttr($index) ?>-main"
                    class="level-0"
                >
                    <div
                        class="flex items-center transition-transform duration-150 ease-in-out transform"
                        :class="{
                            'open' : mobilePanelActiveId,
                            'close' : !mobilePanelActiveId
                        }"
                    >
                        <?php if (!empty($menuItem['childData'])): ?>
                            <span
                                class="flex items-center w-full px-8 py-4 border-b cursor-pointer border-pearl font-semibold level-0"
                                title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                            >
                                <?= $escaper->escapeHtml($menuItem['name']) ?>
                            </span>
                        <?php else: ?>
                            <a
                                class="flex items-center w-full px-8 py-4 border-b cursor-pointer border-pearl font-semibold level-0"
                                href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                                title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                            >
                                <?= $escaper->escapeHtml($menuItem['name']) ?>
                            </a>
                        <?php endif; ?>
                        <?php if (!empty($menuItem['childData'])): ?>
                            <button
                                @click="openSubcategory('<?= /* @noEscape */ $index ?>')"
                                class="absolute right-0 flex items-center justify-center w-11 h-11 mr-8 cursor-pointer
                                border-container"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Open %1 subcategories', $menuItem['name'])) ?>"
                                aria-haspopup="true"
                                :aria-expanded="mobilePanelActiveId === '<?= /* @noEscape */ (string) $index ?>'"
                            >
                                <div class="w-8 h-8 rounded">
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" class="w-full h-full p-1" width="24" height="24" aria-hidden="true"
                                         :class="{
                                'rotate-0': mobilePanelActiveId !== '<?= /* @noEscape */ (string) $index ?>',
                                'rotate-180': mobilePanelActiveId === '<?= /* @noEscape */ (string) $index ?>'
                            }">
                                        <path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7"></path>
                                    </svg>
                                </div>
                            </button>
                        <?php endif; ?>
                    </div>
                    <?php if (!empty($menuItem['childData'])): ?>
                        <div
                            data-child-id="<?= $escaper->escapeHtmLAttr($index) ?>"
                            class="z-10 flex flex-col gap-1 w-full h-full  bg-white"
                            :class="{
                                'hidden': mobilePanelActiveId !== '<?= /* @noEscape */ (string) $index ?>',
                                'block': mobilePanelActiveId === '<?= /* @noEscape */ (string) $index ?>'
                            }"
                        >
                            <ul
                                class="transition-transform duration-200 ease-in-out translate-x-full transform"
                                :class="{
                                    'translate-x-full' : mobilePanelActiveId !== '<?= /* @noEscape */ (string) $index ?>',
                                    'translate-x-0' : mobilePanelActiveId === '<?= /* @noEscape */ (string) $index ?>',
                                }"
                                aria-label="<?= $escaper->escapeHtmlAttr(__('Subcategories')) ?>"
                            >
                                <li>
                                    <a
                                        href="<?= $escaper->escapeUrl($menuItem['url']) ?>"
                                        title="<?= $escaper->escapeHtmlAttr($menuItem['name']) ?>"
                                        class="flex items-center w-full px-8 py-4 border-b cursor-pointer border-pearl"
                                    >
                                        <span class="ml-5">
                                            <?= $escaper->escapeHtml(__('View All')) ?>
                                        </span>
                                    </a>
                                </li>
                                <?php foreach ($menuItem['childData'] as $subMenuItem): ?>
                                    <li>
                                        <a
                                            href="<?= $escaper->escapeUrl($subMenuItem['url']) ?>"
                                            title="<?= $escaper->escapeHtmlAttr($subMenuItem['name']) ?>"
                                            class="flex items-center w-full px-8 py-4 border-b cursor-pointer border-pearl"
                                        >
                                            <span class="ml-5">
                                                <?= $escaper->escapeHtml($subMenuItem['name']) ?>
                                            </span>
                                        </a>
                                    </li>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                    <?php endif; ?>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</nav>
<script>
    'use strict';

    const initMenuMobile<?= $escaper->escapeHtml($uniqueId) ?> = () => {
        return {
            mobilePanelActiveId: null,
            open: false,
            setActiveMenu(menuNode) {
                Array.from(menuNode.querySelectorAll('a')).filter(link => {
                    return link.href === window.location.href.split('?')[0];
                }).map(item => {
                    item.classList.add('text-copper');
                    if(item.closest('li.level-0') &&
                        item.closest('li.level-0').querySelector('a.level-0')  != null){
                        item.closest('li.level-0') &&
                        item.closest('li.level-0').querySelector('a.level-0').classList.add('text-copper');
                    }
                });
            },
            openMenu() {
                this.open = true
                this.$nextTick(() => hyva.trapFocus(this.$refs['mobileMenuNavLinks']));
                // Prevent from body scrolling while mobile menu opened
                document.body.style.overflow = 'hidden';
            },
            closeMenu() {
                document.body.style.overflow = '';

                if (this.open) {
                    this.$nextTick(() => this.$refs['mobileMenuTrigger'].focus() || hyva.releaseFocus());
                }

                this.open = false
                this.mobilePanelActiveId = null
            },
            openSubcategory(index) {
                const menuNodeRef = document.querySelector('[data-child-id=' + index + ']')
                this.mobilePanelActiveId = this.mobilePanelActiveId === index ? 0 : index
                this.$nextTick(() => hyva.trapFocus(menuNodeRef))
            },
            backToMainCategories(index) {
                const menuNodeRef = document.querySelector('[data-child-id=' + index + ']')
                this.mobilePanelActiveId = 0
                this.$nextTick(() => {
                    hyva.trapFocus(this.$refs['mobileMenuNavLinks'])
                    menuNodeRef.querySelector('a').focus()
                })
            }
        }
    }
</script>
