<?php

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\HeroiconsSolid;
use Magento\Framework\Escaper;
use Magento\Wishlist\Block\Cart\Item\Renderer\Actions\MoveToWishlist;

/** @var MoveToWishlist $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

?>
<?php if ($block->isAllowInCart() && $block->isProductVisibleInSiteVisibility()): ?>
    <button
        type="button"
        class="towishlist"
        x-data
        @click.prevent='hyva.postForm(<?= /* @noEscape */ $block->getMoveFromCartParams() ?>)'
        title="<?= $escaper->escapeHtmlAttr(__('Move to Wishlist')) ?>"
        aria-label="<?= $escaper->escapeHtmlAttr(__('Move to Wishlist')) ?>"
    >
        <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.501 5.501 0 0 0-7.78 7.78L12 21.23l8.84-8.84a5.5 5.5 0 0 0 0-7.78" stroke="#A36638" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"/>
        </svg>
    </button>
<?php endif ?>
